---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nggovern/public_html/fundapi

    - cd /home/nggovern/public_html/fundapi || exit 1

    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build

    # restart app (if using cPanel Node.js App)
    - /bin/touch tmp/restart.txt