---
deployment:
  tasks:
    - cd /home/nggovern/repositories/fund-dashboard-frontend || exit 1

    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build

    - export DEPLOYPATH=/home/nggovern/public_html/fundapi

    - /bin/rm -rf $DEPLOYPATH/*

    # adjust based on framework:
    - /bin/cp -R out/* $DEPLOYPATH/
